### ISSUE TITLE
Protozaur WARNING

### ISSUE THREAD

**Issue by nazarok** [DeployRB/Rails5App#6]
> WARNING on line 32 of /home/vagrant/.rvm/gems/ruby-2.4.0/bundler/gems/protozaur-a39e67a7b0cf/app/assets/stylesheets/ptz/inputs_buttons/fileinputs.sass:
> This selector doesn't have any properties and will not be rendered.

P.S.: maybe this off topic

**Comment by the-teacher** [comment]
@nazarok hello! yeah, I know, nothing special, I just didn't finish it yet. But thanks!
